sudo: required
language: generic
serivces:
  -docker

before_install:
  - docker build -t mehrtest/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehrtest/docker-react npm run test