sudo: required
language: generic
serivces:
  -docker

before_install:
  - docker build -t Mehrnaz-A/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Mehrnaz-A/docker-react npm run test